management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

server:
  connection-timeout: 5s
  port: 8080
  tomcat:
    accesslog:
      pattern: "%t %D %s %b %a %m %U %q \"%{Referer}i\" \"%{User-Agent}i\""
      rename-on-rotate: true
      enabled: true
      directory: logs
    basedir:

cache:
  maxSize: 10000
  expirationInMin: 1440 # 1 day
  initialSize: 2000

logging:
  level:
    root: INFO
    com.wearewaes.techassignment.aaroncastro.scalableweb: INFO
  path: logs
